### ISSUE TITLE
signOut() doesn't destroy Hoodie's record of session in browser

### ISSUE THREAD

**Issue by timblack1** [timblack1/hoodie-accountbar#2]
When I sign out a user, Hoodie appears to not destroy that user's session.  The hard evidence is that:
1.  Hoodie continues to ping the server (to keep that user's session alive?) at BOTH that user's API endpoint (e.g., /_api/?hoodieId=lhxc60o) AND at the anonymous user's API endpoint (e.g., /_api/?hoodieId=nve83kl).  It should ping only the anonymous user's API endpoint instead.
2.  When I sign up as a new user then write to the database, user 2's writes end up in user 1's database in CouchDB.  It should write user 2's doc to user 2's database instead.

Why is Hoodie doing this and how can I get it to work correctly?

@gr2m, I tried to replicate this error outside my own application in a test environment, and was not able to replicate it.  So now I should try to figure out what is different between my app and the test environment.  So I don't need you to follow up on this yet.

---

The steps I followed to attempt to replicate the error are as follows.

Create a Polymer app:

`$ yo polymer`

Add hoodie-accountbar as a dependency in bower.json:

```
"hoodie-accountbar": "latest"
```

Install hoodie-accountbar:

`$ bower install`

Copy the following two files into your app's root directory:

gulpfile.js - https://gist.github.com/timblack1/18242e8db18ad2049760
package.json - https://gist.github.com/timblack1/969bd5111cbf5defae90

Install Hoodie & Gulp dependencies

`$ npm install`

Import hoodie-accountbar into app/elements/elements.html by pasting in the following:

```
<link rel="import" href="../bower_components/hoodie-accountbar/hoodie-accountbar.html">
```

Place hoodie-accountbar somewhere visible within the <body> element in app/index.html:

```
<hoodie-accountbar></hoodie-accountbar>
```

Optionally comment out the `<platinum-sw-register>` element (and if you've already loaded the app in your browser, unregister the service worker at chrome://serviceworker-internals/) to disable the service worker cache.

Serve the app:

`$ gulp serve`

(As an alternative, you can use `$ gulp hoodie` to first dynamically generate hoodie.js containing your specific set of Hoodie plugins and write it to the hoodie-service element's directory, then it runs `gulp serve` for you once that is done.)

Sign up a user using the buttons & dialogs.  Write a doc to the database:

`$ document.querySelector('hoodie-accountbar').hoodie.store.add('test', {'test':'test1'})`

Sign out.  Watch your network tab for a few minutes to see if Hoodie keeps pinging the signed-out user's API endpoint.

Sign up a new user and write a new doc to the database.  See if that doc goes to the correct user database at http://localhost:3004/_utils.

**Comment by timblack1** [comment]
This seems to be resolved now that I'm loading hoodie-accountbar as a bower dependency rather than as a custom element.  Why it's resolved, I don't know.

**Comment by timblack1** [comment]
Hm.  No, the error is not resolved.  Reopening the issue.

**Comment by timblack1** [comment]
So the problem was that `<hoodie-service>` instantiates Hoodie via `new Hoodie()`, and I used one copy of `<hoodie-service>` inside `<hoodie-accountbar>`, then used another copy of `<hoodie-service>` inside my custom form element.  The effect was that two copies of Hoodie were instantiated.  What needs to be done instead is to only instantiate one copy of Hoodie via only one `<hoodie-service>` element, then pass that one copy around using data binding.

**Comment by gr2m** [comment]
Ah, that makes sense, thanks for the explanation @timblack1

**Comment by timblack1** [comment]
While this was a problem that was easy for me to correct in my own app's structure, yet it was hard to debug.  So I wonder whether it would be wise for Hoodie to keep a Window-global register of Hoodie instances, keyed by their `baseUrl`s, so as to not allow two Hoodie instances with the same `baseUrl` in the same Window.  Which is the more common use-case:  accidentally creating two Hoodie instances, or intentionally creating two Hoodie instances (effectively two users in one app)?  If both use-cases are expected, then it might not be wise to force users to use only one.

**Comment by gr2m** [comment]
@timblack1 with next hoodie, we'll get rid of the `new Hoodie()` initialisation, there will be only one `hoodie` api on `window`. Having two Hoodie instances on same page is not a use case that ever came up.

**Comment by timblack1** [comment]
:+1:
